name: tekartik_ftp_client_io
description: IO client implementation
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  tekartik_ftp:
    git:
      url: https://github.com/tekartik/ftp.dart
      ref: dart3a
      path: ftp
  # Tmp override
  ftpconnect:
    git:
      url: https://github.com/tekartikdev/dartFTP
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a

dev_dependencies:
  lints: ">=5.0.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
  test: ">=1.24.0"
resolution: workspace

